(() => {
  const grid=document.getElementById("leagueGrid"), lastUpdated=document.getElementById("lastUpdated"), statusText=document.getElementById("statusText"), refreshButton=document.getElementById("refreshButton"), dialog=document.getElementById("matchupsDialog"), dialogName=document.getElementById("dialogLeagueName"), dialogContent=document.getElementById("dialogContent"), closeDialog=document.getElementById("closeDialog"), expanded=new Set();
  let data=null, checking=false;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const pts=v=>v==null?"—":Number(v||0).toFixed(2);
  const ordinal=n=>n+(n%100>=11&&n%100<=13?"th":({1:"st",2:"nd",3:"rd"}[n%10]||"th"));
  const statusClass=s=>["OUT","DOUBTFUL","IR","PUP","SUSPENDED"].includes(String(s).toUpperCase())?"status-out":String(s).toUpperCase()==="QUESTIONABLE"?"status-questionable":"";
  function playerHtml(p,key,bench=false){const open=expanded.has(key);return `<button class="player ${statusClass(p.status)}" data-player="${esc(key)}" type="button" aria-expanded="${open}"><span class="position">${bench?"BN":esc(p.pos)}</span><span><span class="player-name">${esc(p.name)}${p.status?`<span class="player-status">${esc(p.status)}</span>`:""}</span><span class="player-detail">${esc(p.nfl)} ${p.game?"• "+esc(p.game):""}</span></span><span class="player-score">${pts(p.score)}</span>${open?`<span class="player-detail-panel"><span class="stats"><span>Actual: ${pts(p.score)}</span><span>Proj: ${pts(p.projection)}</span><span>${esc(p.stats||"Stats unavailable")}</span></span>${p.news?`<span class="news">${esc(p.news)}</span>`:""}</span>`:""}</button>`}
  function positionKey(p){const x=String(p?.pos||"").toUpperCase();return x==="D/ST"||x==="DST"?"DST":x==="FLEX"?"FLEX":x;}
  function syncStarters(a,b){
    const order=["QB","RB","WR","TE","FLEX","K","DST"];
    const aa=a.players?.starters||[], bb=b.players?.starters||[];
    const usedA=new Set(), usedB=new Set(), rows=[];
    for(const pos of order){
      const ai=aa.map((p,i)=>[p,i]).filter(([p,i])=>!usedA.has(i)&&positionKey(p)===pos);
      const bi=bb.map((p,i)=>[p,i]).filter(([p,i])=>!usedB.has(i)&&positionKey(p)===pos);
      const n=Math.max(ai.length,bi.length);
      for(let i=0;i<n;i++){const ap=ai[i],bp=bi[i];if(ap)usedA.add(ap[1]);if(bp)usedB.add(bp[1]);rows.push({a:ap?.[0]||null,b:bp?.[0]||null});}
    }
    const leftoversA=aa.map((p,i)=>[p,i]).filter(([p,i])=>!usedA.has(i));
    const leftoversB=bb.map((p,i)=>[p,i]).filter(([p,i])=>!usedB.has(i));
    const n=Math.max(leftoversA.length,leftoversB.length);
    for(let i=0;i<n;i++) rows.push({a:leftoversA[i]?.[0]||null,b:leftoversB[i]?.[0]||null});
    return rows;
  }
  function playerPlaceholder(){return '<div class="player player-placeholder" aria-hidden="true"><span></span><span></span><span></span></div>';}
  function playersHtml(leagueId,team,teamKey,force=false,starterOverride=null){
    const key=leagueId+":"+teamKey;if(!force&&!expanded.has(key))return"";
    const starters=starterOverride||team.players?.starters||[],bench=team.players?.bench||[],benchKey=key+":bench",benchOpen=expanded.has(benchKey);
    return `<div class="players-panel"><div class="player-section-title">STARTERS</div>${starters.length?starters.map((p,i)=>p?playerHtml(p,key+":s:"+i):playerPlaceholder()).join(""):'<p class="muted">No starter data returned.</p>'}${bench.length?`<div class="bench-section"><button class="secondary-button" data-bench="${esc(benchKey)}" type="button">${benchOpen?"Hide":"Show"} Bench (${bench.length})</button>${benchOpen?bench.map((p,i)=>playerHtml(p,key+":b:"+i,true)).join(""):""}</div>`:""}</div>`;
  }
  function cardHtml(l){const my=l.matchup?.myTeam||{},opp=l.matchup?.opponent||{},key=l.id+":my",open=expanded.has(key),win=l.matchup?.winProbability??null;return `<article class="league-card"><div class="league-top"><div><h3 class="league-name">${esc(l.name)}</h3><p class="league-meta">${esc(l.platform)} • Week ${l.week||data.week}</p></div><div class="record"><strong>${esc(l.record||"—")}</strong><span>${l.rank?ordinal(l.rank)+" place":"Rank unavailable"}</span></div></div><div class="matchup"><div class="team-row mine"><div><div class="team-name">${esc(my.name)}</div><div class="team-sub">You</div></div><div class="score">${pts(my.score)}</div></div><div class="team-row"><div><div class="team-name">${esc(opp.name)}</div><div class="team-sub">Opponent</div></div><div class="score">${pts(opp.score)}</div></div><div class="matchup-summary"><div class="projection-line"><span>Projected ${pts(my.projection)} – ${pts(opp.projection)}</span><strong>${win==null?"Win chance unavailable":win+"% win chance"+(l.winProbabilityEstimated?"*":"")}</strong></div><div class="win-meter">${win==null?"":`<span class="win-marker" style="left:calc(${Math.max(0,Math.min(100,win))}% - 1.5px)"></span>`}</div>${l.winProbabilityEstimated?'<div class="team-sub" style="margin-top:6px">* Estimated from projected scores</div>':""}</div>${open?(()=>{const rows=syncStarters(my,opp);const myAligned=rows.map(r=>r.a);const oppAligned=rows.map(r=>r.b);return `<div class="matchup-players"><div class="player-column"><div class="player-team-heading">${esc(my.name)}</div>${playersHtml(l.id,my,"my",true,myAligned)||""}</div><div class="player-column"><div class="player-team-heading opponent-heading">${esc(opp.name)}</div>${playersHtml(l.id,opp,"opp",true,oppAligned)||""}</div></div>`;})():""}</div><div class="card-actions"><button class="secondary-button" data-expand="${esc(key)}" type="button">${open?"Hide Players":"Show Players"}</button><button class="secondary-button" data-matchups="${esc(l.id)}" type="button">All Matchups →</button></div></article>`}
  function formatAge(iso){if(!iso)return "—";const sec=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/1000));if(sec<10)return "just now";if(sec<60)return sec+"s ago";const min=Math.floor(sec/60);if(min<60)return min+"m ago";const hr=Math.floor(min/60);return hr+"h "+(min%60)+"m ago"}
  function renderStatus(message,kind="live"){statusText.innerHTML=`<span class="data-status data-status-${kind}"><i></i>${esc(message)}</span>`}
  function render(){if(!data)return;grid.innerHTML=data.leagues.map(cardHtml).join("");lastUpdated.textContent=new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit",second:"2-digit"}).format(new Date(data.updatedAt));const issues=data.errors?.length?` • ${data.errors.length} connection issue${data.errors.length===1?"":"s"}`:"";if(!checking)renderStatus(`Server data ${formatAge(data.updatedAt)} • ${data.leagues.length}/8 leagues connected${issues}`,issues?"warning":"live")}
  function dialogHtml(l){dialogName.textContent=l.name;if(!l.matchups?.length){dialogContent.innerHTML='<div class="dialog-matchups"><p class="muted">No matchup rows were returned for this league.</p></div>';return}dialogContent.innerHTML='<div class="dialog-matchups">'+l.matchups.map((m,mi)=>{const mk=l.id+":all:"+m.id,open=expanded.has(mk);return `<section class="dialog-matchup">${m.teams.map(t=>`<div class="team-row"><div><div class="team-name">${esc(t.name)}</div><div class="team-sub">Projected ${pts(t.projection)}</div></div><div class="score">${pts(t.score)}</div></div>`).join("")}<div class="card-actions"><button class="secondary-button" data-dialog-expand="${esc(mk)}" type="button">${open?"Hide Players":"Show Players"}</button></div>${open?(()=>{const rows=m.teams.length===2?syncStarters(m.teams[0],m.teams[1]):m.teams.map(t=>({a:t.players?.starters||[],b:[]}));return `<div class="matchup-players">${m.teams.map((t,ti)=>{const aligned=m.teams.length===2?rows.map(r=>ti===0?r.a:r.b):t.players?.starters||[];return `<div class="player-column"><div class="player-team-heading">${esc(t.name)}</div>${playersHtml(l.id,t,"all-"+mi+"-"+ti,true,aligned)||""}</div>`}).join("")}</div>`;})():""}</section>`}).join("")+'</div>'}
  grid.addEventListener("click",e=>{const a=e.target.closest("[data-expand]");if(a){expanded.has(a.dataset.expand)?expanded.delete(a.dataset.expand):expanded.add(a.dataset.expand);render();return}const b=e.target.closest("[data-bench]");if(b){expanded.has(b.dataset.bench)?expanded.delete(b.dataset.bench):expanded.add(b.dataset.bench);render();return}const p=e.target.closest("[data-player]");if(p){expanded.has(p.dataset.player)?expanded.delete(p.dataset.player):expanded.add(p.dataset.player);render();return}const m=e.target.closest("[data-matchups]");if(m){const l=data.leagues.find(x=>x.id===m.dataset.matchups);if(l){dialogHtml(l);dialog.showModal?.()}}});
  dialogContent.addEventListener("click",e=>{const b=e.target.closest("[data-dialog-expand]");if(!b)return;expanded.has(b.dataset.dialogExpand)?expanded.delete(b.dataset.dialogExpand):expanded.add(b.dataset.dialogExpand);dialogHtml(data.leagues.find(l=>b.dataset.dialogExpand.startsWith(l.id)))});
  closeDialog.addEventListener("click",()=>dialog.close());
  async function loadLiveData(){const res=await fetch("data/live-data.json?ts="+Date.now(),{cache:"no-store"});if(!res.ok)throw new Error("Live data file returned "+res.status);return res.json()}
  async function refresh(){if(checking)return;checking=true;refreshButton.disabled=true;refreshButton.innerHTML="↻ Checking…";renderStatus("Checking for a newer server snapshot…","checking");const previousUpdated=data?.updatedAt||null;try{const next=await loadLiveData();data=next;render();if(previousUpdated&&next.updatedAt===previousUpdated)renderStatus(`No new server data yet • Last update ${formatAge(next.updatedAt)}`,"waiting");else renderStatus(`Updated just now • ${next.leagues.length}/8 leagues connected`,"updated")}catch(e){renderStatus("Could not check for new data • Showing last snapshot","error")}finally{checking=false;refreshButton.disabled=false;refreshButton.innerHTML="↻ Check for Update"}}
  refreshButton.addEventListener("click",refresh);setInterval(refresh,30000);refresh();setInterval(()=>{if(data&&!checking)renderStatus(`Server data ${formatAge(data.updatedAt)} • ${data.leagues.length}/8 leagues connected`,data.errors?.length?"warning":"live")},1000);
})();